package com.example.demo;

import com.example.demo.user.controller.UserController;
import com.example.demo.user.model.User;
import com.example.demo.user.service.UserService;
import com.example.demo.user.utils.UserRole;
import com.github.javafaker.Faker;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class DemoApplicationTests {

	@Autowired
	private UserService userService;

	@Autowired
	private UserController userController;

	private static Faker faker = new Faker();

	@BeforeAll
	static void initializeSampleData() {

	}

	@Test
	void contextLoads() {

	}

	@Test
	void addUserToRepo() {
		User testUser = User.builder()
				.username("Username1")
				.password("Password")
				.role(UserRole.USER)
				.build();

		User userInDb = userService.addUser(testUser);
		Assertions.assertEquals(testUser, userInDb);
	}

	@Test
	void addedUserHaveAutoGeneratedId() {
		User testUser1 = User.builder()
				.username("Username1")
				.password("Password")
				.build();

		User testUser2 = User.builder()
				.username("Username2")
				.password("Password")
				.build();

		User user1InDb = userService.addUser(testUser1);
		User user2InDb = userService.addUser(testUser2);
		Assertions.assertEquals(user1InDb.getId() + 1, user2InDb.getId());
	}
}
